### ISSUE TITLE
Some documentation questions

### ISSUE THREAD

**Issue by genobobeno** [ropensci-archive/solrium#125]
Hello solrium creators! I'm brand new to Solr and trying to run some very basic commands and hoping solrium can help out but I'm running into trouble at the outset.

I'd like to get started with solrium by mimicking the exact process as shown in the SQL JDBC connection below, but the documentation doesn't seem to help with:
a) authentication... which means I can't even try to access anything (SolrClient$new(proxy = list())) doesn't make sense because it's not a proxy... I'm trying to query the host. I tried the proxy = list(url = "myExternalServer:myPort", user="myUsername", pwd="myPassword") but it didn't work.
b) searching a collection. The documentation describes "managing" collections, but not much about choosing one. I assume it's the SolrClient$new(path="myCollection/search"), but I can't test it cause I can't login.

I've been able to create a JDBC connection... This allows me to run Solr's SQL engine. 

```{r} 
solrCP <- c("~/SolrJars/solr-solrj-8.4.1.jar",
            list.files('~/SolrJars/dist', pattern='jar', full.names=TRUE),
            list.files('~/SolrJars/dist/solrj-lib', pattern='jar', full.names=TRUE))
drv <- JDBC(driverClass = 'org.apache.solr.client.solrj.io.sql.DriverImpl', 
            classPath = solrCP, identifier.quote="`") 
dbConnect(drv,'jdbc:solr://myExternalServer:2181?collection=myCollection','myUsername,'myPassword')
```

**Comment by sckott** [comment]
Thanks for the issue. I maintained solrium for a previous job that I've left. I no longer maintain the package. I've not been able to find a new maintainer. If you're interested let me know, or know of anyone interested

**Comment by genobobeno** [comment]
If I could figure out how to login, I might be interested in maintenance

**Comment by sckott** [comment]
Yeah, i here you on the frustration about logging in. There's so many different authorization scenarios though it's hard for me to test all of them, and given i'm in a new job now, I can't really help.

**Comment by maelle** [comment]
This repository is about to be archived.
